Feat 14 get user
YaronAvraham93/budgetApp pull request #16
Opened 2021-04-19 11:01 UTC by YaronAvraham93

2021-04-19 13:16 UTC, IsaacM890 requested changes

2021-04-19 13:16 UTC, IsaacM890 commented on budget-app/src/components/molecules/Activity/ActivitesChart.tsx
> +  const helperIncome: any = {};
should ne dynamic function 
export it to helpers/utils folder

2021-04-19 13:16 UTC, IsaacM890 commented on budget-app/src/components/organisms/Sidebar/Sidebar.tsx
> +const Sidebar: React.FC = () => {
maybe "NavBar" is better name

2021-04-19 13:16 UTC, IsaacM890 commented on budget-app/src/components/organisms/UserInfro/UserInfro.tsx
> +const UserInfro: React.FC = () => {
typo == > "UserInfo" not "UserInfro"

2021-04-20 05:46 UTC, almogbhl requested changes

2021-04-20 05:46 UTC, almogbhl commented on budget-app/src/contexts/userReducer.ts
> +    case 'SET_USER':
constant

2021-04-20 05:46 UTC, almogbhl commented on budget-app/src/helpers/totalAmountByPaymentType.ts
> +  // const helperExpenses: any = {};
rm unused code

2021-04-20 05:46 UTC, almogbhl commented on budget-app/src/helpers/totalAmountByPaymentType.ts
> +        helper[date] = +transaction.amount;
+=

2021-04-20 05:46 UTC, almogbhl commented on budget-app/src/helpers/totalAmountByPaymentType.ts
> +    if (transaction.paymentType === Type) {
u wish to do something else if the type is income or expense

2021-04-20 05:46 UTC, almogbhl commented on budget-app/src/models/index.tsx
> +  last4Digits: Number;
number

2021-04-20 16:52 UTC, almogbhl approved these changes

2021-04-20 16:52 UTC, almogbhl commented on budget-app/src/models/index.tsx
> +  amount: number;
string

2021-04-20 16:58 UTC, merged